INSERT INTO PESSOA (NOME, TELEFONE, EMAIL) VALUES ('Luke Skywalker', '91111-1111', 'luke@email.com');
INSERT INTO PESSOA (NOME, TELEFONE, EMAIL) VALUES ('Leia Skywalker', '92222-2222', 'leia@email.com');
INSERT INTO PESSOA (NOME, TELEFONE, EMAIL) VALUES ('Vader', '93333-3333', 'vader@email.com');